//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev.craftengine.editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dev.craftengine.editor.Resources.Resources.de-DE", typeof(Resources_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über CraftEngine.
        /// </summary>
        public static string about_ce {
            get {
                return ResourceManager.GetString("about.ce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        public static string about_title {
            get {
                return ResourceManager.GetString("about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string asset_browser_back_folder {
            get {
                return ResourceManager.GetString("asset_browser.back_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Metadaten.
        /// </summary>
        public static string asset_browser_context_common_metadata {
            get {
                return ResourceManager.GetString("asset_browser.context.common.metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string asset_browser_context_common_new {
            get {
                return ResourceManager.GetString("asset_browser.context.common.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuladen.
        /// </summary>
        public static string asset_browser_context_common_reload {
            get {
                return ResourceManager.GetString("asset_browser.context.common.reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Explorer Zeigen.
        /// </summary>
        public static string asset_browser_context_common_show_explorer {
            get {
                return ResourceManager.GetString("asset_browser.context.common.show_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Finder Zeigen.
        /// </summary>
        public static string asset_browser_context_common_show_finder {
            get {
                return ResourceManager.GetString("asset_browser.context.common.show_finder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In File Explorer Zeigen.
        /// </summary>
        public static string asset_browser_context_common_show_in_files {
            get {
                return ResourceManager.GetString("asset_browser.context.common.show_in_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad Kopieren.
        /// </summary>
        public static string asset_browser_context_copy_path {
            get {
                return ResourceManager.GetString("asset_browser.context.copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string asset_browser_context_open {
            get {
                return ResourceManager.GetString("asset_browser.context.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne in {program}.
        /// </summary>
        public static string asset_browser_context_open_external {
            get {
                return ResourceManager.GetString("asset_browser.context.open.external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbenennen.
        /// </summary>
        public static string asset_browser_context_rename {
            get {
                return ResourceManager.GetString("asset_browser.context.rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        public static string asset_browser_new_folder {
            get {
                return ResourceManager.GetString("asset_browser.new.folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string asset_browser_new_level {
            get {
                return ResourceManager.GetString("asset_browser.new.level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string asset_browser_search {
            get {
                return ResourceManager.GetString("asset_browser.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Java {version} herunter.
        /// </summary>
        public static string client_launcher_download_java_title {
            get {
                return ResourceManager.GetString("client_launcher.download.java.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Bibliotheken herunter.
        /// </summary>
        public static string client_launcher_download_libraries_title {
            get {
                return ResourceManager.GetString("client_launcher.download.libraries.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Version herunter.
        /// </summary>
        public static string client_launcher_download_version_title {
            get {
                return ResourceManager.GetString("client_launcher.download.version.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Minecraft {version}....
        /// </summary>
        public static string client_launcher_launch_title {
            get {
                return ResourceManager.GetString("client_launcher.launch.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbauswahl.
        /// </summary>
        public static string colorpicker_title {
            get {
                return ResourceManager.GetString("colorpicker.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string common_copy {
            get {
                return ResourceManager.GetString("common.copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string common_delete {
            get {
                return ResourceManager.GetString("common.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade....
        /// </summary>
        public static string common_loading_title {
            get {
                return ResourceManager.GetString("common.loading.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        public static string common_paste {
            get {
                return ResourceManager.GetString("common.paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bearbeiten.
        /// </summary>
        public static string editor_menubar_edit {
            get {
                return ResourceManager.GetString("editor.menubar.edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string editor_menubar_edit_preferences {
            get {
                return ResourceManager.GetString("editor.menubar.edit.preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellen.
        /// </summary>
        public static string editor_menubar_edit_redo {
            get {
                return ResourceManager.GetString("editor.menubar.edit.redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig.
        /// </summary>
        public static string editor_menubar_edit_undo {
            get {
                return ResourceManager.GetString("editor.menubar.edit.undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Datei.
        /// </summary>
        public static string editor_menubar_file {
            get {
                return ResourceManager.GetString("editor.menubar.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Bauen.
        /// </summary>
        public static string editor_menubar_file_build {
            get {
                return ResourceManager.GetString("editor.menubar.file.build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string editor_menubar_file_exit {
            get {
                return ResourceManager.GetString("editor.menubar.file.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf CraftUniverse Veröffentlichen.
        /// </summary>
        public static string editor_menubar_file_publish_cu {
            get {
                return ResourceManager.GetString("editor.menubar.file.publish_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichere Level.
        /// </summary>
        public static string editor_menubar_file_save_level {
            get {
                return ResourceManager.GetString("editor.menubar.file.save_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichere Level als ....
        /// </summary>
        public static string editor_menubar_file_save_level_as {
            get {
                return ResourceManager.GetString("editor.menubar.file.save_level_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hilfe.
        /// </summary>
        public static string editor_menubar_help {
            get {
                return ResourceManager.GetString("editor.menubar.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über....
        /// </summary>
        public static string editor_menubar_help_about {
            get {
                return ResourceManager.GetString("editor.menubar.help.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string editor_menubar_help_wiki {
            get {
                return ResourceManager.GetString("editor.menubar.help.wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Objekte.
        /// </summary>
        public static string editor_menubar_objects {
            get {
                return ResourceManager.GetString("editor.menubar.objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielen.
        /// </summary>
        public static string editor_menubar_play {
            get {
                return ResourceManager.GetString("editor.menubar.play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft läuft Bereits..
        /// </summary>
        public static string editor_menubar_play_msgbox_running {
            get {
                return ResourceManager.GetString("editor.menubar.play.msgbox.running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Spielen.
        /// </summary>
        public static string editor_menubar_play_online {
            get {
                return ResourceManager.GetString("editor.menubar.play.online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustarten.
        /// </summary>
        public static string editor_menubar_play_restart {
            get {
                return ResourceManager.GetString("editor.menubar.play.restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fenster.
        /// </summary>
        public static string editor_menubar_windows {
            get {
                return ResourceManager.GetString("editor.menubar.windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string messagebox_button_cancel {
            get {
                return ResourceManager.GetString("messagebox.button.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string messagebox_button_no {
            get {
                return ResourceManager.GetString("messagebox.button.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string messagebox_button_okay {
            get {
                return ResourceManager.GetString("messagebox.button.okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string messagebox_button_yes {
            get {
                return ResourceManager.GetString("messagebox.button.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string newproject_button_close {
            get {
                return ResourceManager.GetString("newproject.button.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Erstellen.
        /// </summary>
        public static string newproject_button_create {
            get {
                return ResourceManager.GetString("newproject.button.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel Version:.
        /// </summary>
        public static string newproject_select_version_label {
            get {
                return ResourceManager.GetString("newproject.select.version.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string newproject_textinput_name_label {
            get {
                return ResourceManager.GetString("newproject.textinput.name.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad.
        /// </summary>
        public static string newproject_textinput_path_label {
            get {
                return ResourceManager.GetString("newproject.textinput.path.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Projekt.
        /// </summary>
        public static string newproject_title {
            get {
                return ResourceManager.GetString("newproject.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier ist nichts zusehen.
        /// </summary>
        public static string notifications_common_nothing {
            get {
                return ResourceManager.GetString("notifications.common.nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Editor.
        /// </summary>
        public static string preferences_external_select_audio_label {
            get {
                return ResourceManager.GetString("preferences.external.select.audio.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Editor.
        /// </summary>
        public static string preferences_external_select_coding_label {
            get {
                return ResourceManager.GetString("preferences.external.select.coding.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild Editor.
        /// </summary>
        public static string preferences_external_select_image_label {
            get {
                return ResourceManager.GetString("preferences.external.select.image.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Editor.
        /// </summary>
        public static string preferences_external_select_models_label {
            get {
                return ResourceManager.GetString("preferences.external.select.models.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string preferences_general_select_languages_label {
            get {
                return ResourceManager.GetString("preferences.general.select.languages.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch (Deutschland).
        /// </summary>
        public static string preferences_general_select_languages_options_de_DE {
            get {
                return ResourceManager.GetString("preferences.general.select.languages.options.de-DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch (UK).
        /// </summary>
        public static string preferences_general_select_languages_options_en_GB {
            get {
                return ResourceManager.GetString("preferences.general.select.languages.options.en-GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch (US).
        /// </summary>
        public static string preferences_general_select_languages_options_en_US {
            get {
                return ResourceManager.GetString("preferences.general.select.languages.options.en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch (Frankreich).
        /// </summary>
        public static string preferences_general_select_languages_options_fr_FR {
            get {
                return ResourceManager.GetString("preferences.general.select.languages.options.fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schweizerdeutsch (Schweiz).
        /// </summary>
        public static string preferences_general_select_languages_options_gsw_CH {
            get {
                return ResourceManager.GetString("preferences.general.select.languages.options.gsw-CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string preferences_sidebar_editor {
            get {
                return ResourceManager.GetString("preferences.sidebar.editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe Tools.
        /// </summary>
        public static string preferences_sidebar_external {
            get {
                return ResourceManager.GetString("preferences.sidebar.external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemein.
        /// </summary>
        public static string preferences_sidebar_general {
            get {
                return ResourceManager.GetString("preferences.sidebar.general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leistung.
        /// </summary>
        public static string preferences_sidebar_performance {
            get {
                return ResourceManager.GetString("preferences.sidebar.performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string preferences_title {
            get {
                return ResourceManager.GetString("preferences.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Projekt.
        /// </summary>
        public static string projectlist_buttons_new_project {
            get {
                return ResourceManager.GetString("projectlist.buttons.new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Öffnen.
        /// </summary>
        public static string projectlist_buttons_open_project {
            get {
                return ResourceManager.GetString("projectlist.buttons.open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte Neuladen.
        /// </summary>
        public static string projectlist_buttons_reload_tooltip {
            get {
                return ResourceManager.GetString("projectlist.buttons.reload.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Löschen.
        /// </summary>
        public static string projectlist_list_item_delete_tooltip {
            get {
                return ResourceManager.GetString("projectlist.list.item.delete.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Öffnen.
        /// </summary>
        public static string projectlist_list_item_open_tooltip {
            get {
                return ResourceManager.GetString("projectlist.list.item.open.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string projectlist_list_name_title {
            get {
                return ResourceManager.GetString("projectlist.list.name.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Version.
        /// </summary>
        public static string projectlist_list_version_title {
            get {
                return ResourceManager.GetString("projectlist.list.version.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du sicher, dass du die Dateierweiterung ändern möchtest?.
        /// </summary>
        public static string rename_quest_file_ext_message {
            get {
                return ResourceManager.GetString("rename.quest.file_ext.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du sicher?.
        /// </summary>
        public static string rename_quest_file_ext_title {
            get {
                return ResourceManager.GetString("rename.quest.file_ext.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbenennen.
        /// </summary>
        public static string rename_title {
            get {
                return ResourceManager.GetString("rename.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild von {credit}.
        /// </summary>
        public static string startup_image_credits {
            get {
                return ResourceManager.GetString("startup.image_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade {asset} herunter....
        /// </summary>
        public static string startup_minecraft_asset_download_asset {
            get {
                return ResourceManager.GetString("startup.minecraft_asset.download_asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade index.json herunter....
        /// </summary>
        public static string startup_minecraft_asset_index {
            get {
                return ResourceManager.GetString("startup.minecraft_asset.index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen von index.json Fehlgeschlagen.
        /// </summary>
        public static string startup_minecraft_asset_index_failed {
            get {
                return ResourceManager.GetString("startup.minecraft_asset.index.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuten.
        /// </summary>
        public static string startup_minutes {
            get {
                return ResourceManager.GetString("startup.minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Minecraft Assets herunter....
        /// </summary>
        public static string startup_text_downloading_minecraft_assets {
            get {
                return ResourceManager.GetString("startup.text.downloading_minecraft_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne Projekt....
        /// </summary>
        public static string startup_text_opening_project {
            get {
                return ResourceManager.GetString("startup.text.opening_project", resourceCulture);
            }
        }
    }
}
