name: Build App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        platform: [ win-x64, win-arm64, linux-x64, linux-arm64, osx-arm64 ]
        include:
          - platform: win-x64
            goos: windows
            goarch: amd64
            ext: .exe
          - platform: win-arm64
            goos: windows
            goarch: arm64
            ext: .exe
          - platform: linux-x64
            goos: linux
            goarch: amd64
            ext: ""
          - platform: linux-arm64
            goos: linux
            goarch: arm64
            ext: ""
          - platform: osx-arm64
            goos: darwin
            goarch: arm64
            ext: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Set build OS
        run: echo "BUILD_OS=${{ matrix.platform }}" >> $GITHUB_ENV

      - name: Build for ${{ matrix.platform }}
        run: |
          dotnet publish -c Release -r ${{ matrix.platform }} --self-contained true \
          -p:PublishSingleFile=true -p:PublishTrimmed=true -p:StripSymbols=true \
          -p:InformationalVersion=${{ github.event.inputs.version }} \
          -o build/${{ matrix.platform }}

      - name: Set Environment Variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV
          echo "GIT_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "GENERATOR_OUTPUT_NAME=rungen-${{ matrix.ext }}" >> $GITHUB_ENV

      - name: Run RuntimeGenerator build script
        run: go build -ldflags "-w -X 'main.version=${{ env.GIT_VERSION }}'" -o build/${{ matrix.platform }}/${{ env.GENERATOR_OUTPUT_NAME }} ./RuntimeGenerator/cmd/generator/main.go

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ce-editor_${{ matrix.platform }}
          path: build/${{ matrix.platform }}
